In [1]:
import httpx
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime
import time
import json
import psycopg
import os
import sys
import numpy as np
from dotenv import load_dotenv

sys.path.append(os.path.abspath('./src'))
import db_functions as dbf
load_dotenv()
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST", "localhost")
port = os.getenv("DB_PORT", "5432")
dbname = os.getenv("DB_NAME")
conn_str = f"postgresql://{user}:{password}@{host}:{port}/{dbname}"
api_key = os.getenv("API_KEY")
api_url = 'https://api.stratz.com/graphql'
headers = {
    'User-Agent': 'STRATZ_API',
    "Authorization": f"Bearer {api_key}"
}

In [ ]:
# with psycopg.connect(conn_str) as conn:
#     with conn.cursor() as cur:
#         result = cur.execute("SELECT table_name FROM information_schema.tables").fetchall()
#         for table_name in result:
#             if table_name[0].startswith('match_'):
#                 cur.execute(f'DROP TABLE {table_name[0]}')

In [15]:
## Parsing matches to dataframes and to sql tables
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        match_id_tups = cur.execute("SELECT match_id FROM matches WHERE start_date >= '2025-02-21 00:00:00' ORDER BY start_date ASC;").fetchall()
        match_ids = [tup[0] for tup in match_id_tups]
        parsed_id_tups = cur.execute("SELECT id FROM match_details").fetchall()
        parsed_ids = [tup[0] for tup in parsed_id_tups]
        unfinished_match_ids = []
        for match_id in match_ids:
            if match_id not in parsed_ids:
                unfinished_match_ids.append(match_id)

In [ ]:
nested_vars = []
for key, value in result_json.items():
    if type(value) in [dict, list]:
        print(key, type(value))
        nested_vars.append(key)

pickBans <class 'list'>
chatEvents <class 'list'>
predictedWinRates <class 'list'>
winRates <class 'list'>
radiantNetworthLeads <class 'list'>
radiantExperienceLeads <class 'list'>
radiantKills <class 'list'>
direKills <class 'list'>
towerDeaths <class 'list'>
towerStatus <class 'list'>
players <class 'list'>

In [ ]:
for key, value in result_json['players'][0].items():
    if type(value) in [dict, list]:
        print(key, type(value))
        nested_vars.append(key)

stats <class 'dict'>

In [25]:
for key, value in result_json['players'][0]['stats'].items():
    if type(value) in [dict, list]:
        print(key, type(value))
        nested_vars.append(key)

impPerMinute <class 'list'>
goldPerMinute <class 'list'>
networthPerMinute <class 'list'>
experiencePerMinute <class 'list'>
towerDamagePerMinute <class 'list'>
campStack <class 'list'>
deathEvents <class 'list'>
farmDistributionReport <class 'dict'>
matchPlayerBuffEvent <class 'list'>
inventoryReport <class 'list'>
itemPurchases <class 'list'>
courierKills <class 'list'>
runes <class 'list'>
wards <class 'list'>
wardDestruction <class 'list'>

In [4]:
mid_query = 'SELECT DISTINCT match_id FROM match_players WHERE match_players."steamAccountId" IS NULL'
matches = dbf.query_select_to_df(conn_str, mid_query, 'match_players', columns=['match_id'])
query = '''
    query($id: Long!) {
        match(id: $id) {
            players {
                heroId
                steamAccountId
                partyId
                steamAccount {
                    name
                    realName
                    profileUri
                    timeCreated
                    isAnonymous
                    proSteamAccount {
                        teamId
                        name
                    }
                }
            }
        }
    }
'''
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        for match_id in matches['match_id']:
            result = dbf.query_stratz(query, headers, api_url, variables={'id': match_id})
            res = result['data']['match']['players']
            df_players_addition = pd.DataFrame(res)
            df_steam_account = pd.json_normalize(df_players_addition['steamAccount'])
            og_cols = df_steam_account.columns
            new_cols = [str.replace(colname, '.', '_') for colname in df_steam_account.columns]
            col_mapper = {og_col: new_col for og_col, new_col in zip(og_cols, new_cols)}
            df_steam_account = df_steam_account.rename(col_mapper, axis=1)
            df_players_addition = df_players_addition.drop('steamAccount', axis=1)
            df_players_final = pd.concat([df_players_addition, df_steam_account], axis=1)
            try:
                df_players_final = df_players_final.drop('proSteamAccount', axis=1) #Sometimes this column gets left there empty
            except:
                pass
            for idx, row in df_players_final.iterrows():
                for col in df_players_final.columns:
                    if pd.isna(row[col]):
                        cur.execute(f'UPDATE match_players SET "{col}" = NULL WHERE match_players.match_id = %s AND match_players."heroId" = %s;', (match_id, row['heroId']))
                    else:
                        cur.execute(f'UPDATE match_players SET "{col}" = %s WHERE match_players.match_id = %s AND match_players."heroId" = %s;', (row[col], match_id, row['heroId']))
            conn.commit()

In [34]:
with psycopg.connect(conn_str) as conn:
    cols = []
    for col_name, dtype in zip(df_players_final.columns, df_players_final.dtypes):
        if col_name != 'heroId':
            pg_type = dbf.get_pg_type(dtype)
            # Wrap column names in quotes to handle spaces or reserved words
            cols.append(f'ADD COLUMN"{col_name}" {pg_type}')
    
    schema = ", ".join(cols)
    create_table_query = f'ALTER TABLE "match_players" {schema};'
    with conn.cursor() as cur:
        cur.execute(create_table_query)

In [8]:
queries = [
    'SELECT id FROM league_details ld WHERE ld."displayName" LIKE \'ESL%\' AND ld."prizePool" <> 0;',
    'SELECT id FROM league_details ld WHERE ld."displayName" LIKE \'%DreamLeague%\' AND ld."prizePool" <> 0;',
    'SELECT id FROM league_details ld WHERE ld."displayName" LIKE \'%International%\' AND ld."prizePool" <> 0;',
    'SELECT id FROM league_details ld WHERE ld."displayName" LIKE \'FISSURE%\' AND ld."displayName" NOT LIKE \'%Special\' AND ld."prizePool" <> 0;',
    'SELECT id FROM league_details ld WHERE ld."displayName" LIKE \'%Clavision%\' AND ld."prizePool" <> 0;'
]

In [19]:
league_ids = pd.DataFrame()
for query in queries:
    batch_ids = dbf.query_select_to_df(conn_str, query, 'league_details', columns=['id'])['id'] 
    league_ids = pd.concat([league_ids, batch_ids])
query = '''
    query($id: Int!, $request: LeagueMatchesRequestType!) {
        league(id: $id) {
            matches(request: $request) {
                id
            }
        }
    }
'''
league_ids = league_ids['id']
match_ids = pd.DataFrame(columns=['id'])
for league_id in league_ids:
    skip_counter = 0
    while True:
        results = dbf.query_stratz(
            query, 
            headers, 
            api_url, 
            variables={
                'id': int(league_id), 
                'request': {'isParsed': True, 'take':100, 'skip': skip_counter}})
        results_matches = results['data']['league']['matches']
        skip_counter += 100
        if len(results_matches) == 0:
            break
        match_ids = pd.concat([match_ids, pd.DataFrame(results_matches)], axis=0)
match_ids = match_ids.reset_index().drop(['index'], axis=1)
query = 'SELECT id FROM match_details;'
db_match_ids = dbf.query_select_to_df(conn_str, query, 'match_details', columns=['id'])
for idx, row in match_ids.copy().iterrows():
    if row['id'] in list(db_match_ids['id']):
        match_ids = match_ids.drop(idx, axis=0)

In [2]:
query = 'SELECT id FROM league_details ld WHERE ld."prizePool" > 500000;'
league_ids = dbf.query_select_to_df(conn_str, query, 'league_details', columns=['id'])['id']
query = '''
    query($id: Int!, $request: LeagueMatchesRequestType!) {
        league(id: $id) {
            matches(request: $request) {
                id
            }
        }
    }
'''
match_ids = pd.DataFrame(columns=['id'])
for league_id in league_ids:
    skip_counter = 0
    while True:
        results = dbf.query_stratz(
            query, 
            headers, 
            api_url, 
            variables={
                'id': league_id, 
                'request': {'isParsed': True, 'take':100, 'skip': skip_counter}})
        results_matches = results['data']['league']['matches']
        skip_counter += 100
        if len(results_matches) == 0:
            break
        match_ids = pd.concat([match_ids, pd.DataFrame(results_matches)], axis=0)
match_ids = match_ids.reset_index().drop(['index'], axis=1)
query = 'SELECT id FROM match_details;'
db_match_ids = dbf.query_select_to_df(conn_str, query, 'match_details', columns=['id'])
for idx, row in match_ids.copy().iterrows():
    if row['id'] in list(db_match_ids['id']):
        match_ids = match_ids.drop(idx, axis=0)

In [21]:
match_ids.to_csv('backup.csv')

In [2]:
match_ids = pd.read_csv('backup.csv')
query = 'SELECT id FROM match_details;'
db_match_ids = dbf.query_select_to_df(conn_str, query, 'match_details', columns=['id'])
for idx, row in match_ids.copy().iterrows():
    if row['id'] in list(db_match_ids['id']):
        match_ids = match_ids.drop(idx, axis=0)
match_ids = match_ids.reset_index()
match_ids

      index  Unnamed: 0          id
0       173         444  6158170178
1       174         445  6158081326
2       175         446  6158010330
3       176         447  6157905423
4       177         448  6157810302
...     ...         ...         ...
4043   4216        5804  7868858167
4044   4217        5805  7868771308
4045   4218        5806  7868764939
4046   4219        5807  7868706982
4047   4220        5808  7868705787

[4048 rows x 3 columns]

In [4]:
match_ids = match_ids.drop(range(0, 499), axis=0)
match_ids

      index  Unnamed: 0          id
499     672         943  5645454664
500     673         944  5644626111
501     674         945  5644524719
502     675         946  5644420232
503     676         947  5644313409
...     ...         ...         ...
4043   4216        5804  7868858167
4044   4217        5805  7868771308
4045   4218        5806  7868764939
4046   4219        5807  7868706982
4047   4220        5808  7868705787

[3549 rows x 3 columns]

In [3]:
dbf.query_match(conn_str, headers, api_url, list(match_ids['id']))

Currently processing iteration 0
Currently processing iteration 1
Currently processing iteration 2
Currently processing iteration 3
Currently processing iteration 4
Currently processing iteration 5
Currently processing iteration 6
Currently processing iteration 7
Currently processing iteration 8
Currently processing iteration 9
Currently processing iteration 10
Currently processing iteration 11
Currently processing iteration 12
Currently processing iteration 13
Currently processing iteration 14
Currently processing iteration 15
Currently processing iteration 16
Currently processing iteration 17
Currently processing iteration 18
Currently processing iteration 19
Currently processing iteration 20
Currently processing iteration 21
Currently processing iteration 22
Currently processing iteration 23
Currently processing iteration 24
Currently processing iteration 25
Currently processing iteration 26
Currently processing iteration 27
Currently processing iteration 28
Currently processing iteration 29
Currently processing iteration 30
Currently processing iteration 31
Currently processing iteration 32
Currently processing iteration 33
Currently processing iteration 34
Currently processing iteration 35
Currently processing iteration 36
Currently processing iteration 37
Currently processing iteration 38
Currently processing iteration 39
Currently processing iteration 40
Currently processing iteration 41
Currently processing iteration 42
Currently processing iteration 43
Currently processing iteration 44
Currently processing iteration 45
Currently processing iteration 46
Currently processing iteration 47
Currently processing iteration 48
Currently processing iteration 49
Currently processing iteration 50
Currently processing iteration 51
Currently processing iteration 52
Currently processing iteration 53
Currently processing iteration 54
Currently processing iteration 55
Currently processing iteration 56
Currently processing iteration 57
Currently processing iteration 58
Currently processing iteration 59
Currently processing iteration 60
Currently processing iteration 61
Currently processing iteration 62
Currently processing iteration 63
Currently processing iteration 64
Currently processing iteration 65
Currently processing iteration 66
Currently processing iteration 67
Currently processing iteration 68
Currently processing iteration 69
Currently processing iteration 70
Currently processing iteration 71
Currently processing iteration 72
Currently processing iteration 73
Currently processing iteration 74
Currently processing iteration 75
Currently processing iteration 76
Currently processing iteration 77
Currently processing iteration 78
Currently processing iteration 79
Currently processing iteration 80
Currently processing iteration 81
Currently processing iteration 82
Currently processing iteration 83
Currently processing iteration 84
Currently processing iteration 85
Currently processing iteration 86
Currently processing iteration 87
Currently processing iteration 88
Currently processing iteration 89
Currently processing iteration 90
Currently processing iteration 91
Currently processing iteration 92
Currently processing iteration 93
Currently processing iteration 94
Currently processing iteration 95
Currently processing iteration 96
Currently processing iteration 97
Currently processing iteration 98
Currently processing iteration 99
Currently processing iteration 100
Currently processing iteration 101
Currently processing iteration 102
Currently processing iteration 103
Currently processing iteration 104
Currently processing iteration 105
Currently processing iteration 106
Currently processing iteration 107
Currently processing iteration 108
Currently processing iteration 109
Currently processing iteration 110
Currently processing iteration 111
Currently processing iteration 112
Currently processing iteration 113
Currently processing iteration 114
Currently processing iteration 115
Currently processing iteration 116
Currently processing iteration 117
Currently processing iteration 118
Currently processing iteration 119
Currently processing iteration 120
Currently processing iteration 121
Currently processing iteration 122
Currently processing iteration 123
Currently processing iteration 124
Currently processing iteration 125
Currently processing iteration 126
Currently processing iteration 127
Currently processing iteration 128
Currently processing iteration 129
Currently processing iteration 130
Currently processing iteration 131
Currently processing iteration 132
Currently processing iteration 133
Currently processing iteration 134
Currently processing iteration 135
Currently processing iteration 136
Currently processing iteration 137
Currently processing iteration 138
Currently processing iteration 139
Currently processing iteration 140
Currently processing iteration 141
Currently processing iteration 142
Currently processing iteration 143
Currently processing iteration 144
Currently processing iteration 145
Currently processing iteration 146
Currently processing iteration 147
Currently processing iteration 148
Currently processing iteration 149
Currently processing iteration 150
Currently processing iteration 151
Currently processing iteration 152
Currently processing iteration 153
Currently processing iteration 154
Currently processing iteration 155
Currently processing iteration 156
Currently processing iteration 157
Currently processing iteration 158
Currently processing iteration 159
Currently processing iteration 160
Currently processing iteration 161
Currently processing iteration 162
Currently processing iteration 163
Currently processing iteration 164
Currently processing iteration 165
Currently processing iteration 166
Currently processing iteration 167
Currently processing iteration 168
Currently processing iteration 169
Currently processing iteration 170
Currently processing iteration 171
Currently processing iteration 172
Currently processing iteration 173
Currently processing iteration 174
Currently processing iteration 175
Currently processing iteration 176
Currently processing iteration 177
Currently processing iteration 178
Currently processing iteration 179
Currently processing iteration 180
Currently processing iteration 181
Currently processing iteration 182
Currently processing iteration 183
Currently processing iteration 184
Currently processing iteration 185
Currently processing iteration 186
Currently processing iteration 187
Currently processing iteration 188
Currently processing iteration 189
Currently processing iteration 190
Currently processing iteration 191
Currently processing iteration 192
Currently processing iteration 193
Currently processing iteration 194
Currently processing iteration 195
Currently processing iteration 196
Currently processing iteration 197
Currently processing iteration 198
Currently processing iteration 199
Currently processing iteration 200
Currently processing iteration 201
Currently processing iteration 202
Currently processing iteration 203
Currently processing iteration 204
Currently processing iteration 205
Currently processing iteration 206
Currently processing iteration 207
Currently processing iteration 208
Currently processing iteration 209
Currently processing iteration 210
Currently processing iteration 211
Currently processing iteration 212
Currently processing iteration 213
Currently processing iteration 214
Currently processing iteration 215
Currently processing iteration 216
Currently processing iteration 217
Currently processing iteration 218
Currently processing iteration 219
Currently processing iteration 220
Currently processing iteration 221
Currently processing iteration 222
Currently processing iteration 223
Currently processing iteration 224
Currently processing iteration 225
Currently processing iteration 226
Currently processing iteration 227
Currently processing iteration 228
Currently processing iteration 229
Currently processing iteration 230
Currently processing iteration 231
Currently processing iteration 232
Currently processing iteration 233
Currently processing iteration 234
Currently processing iteration 235
Currently processing iteration 236
Currently processing iteration 237
Currently processing iteration 238
Currently processing iteration 239
Currently processing iteration 240
Currently processing iteration 241
Currently processing iteration 242
Currently processing iteration 243
Currently processing iteration 244
Currently processing iteration 245
Currently processing iteration 246
Currently processing iteration 247
Currently processing iteration 248
Currently processing iteration 249
Currently processing iteration 250
Currently processing iteration 251
Currently processing iteration 252
Currently processing iteration 253
Currently processing iteration 254
Currently processing iteration 255
Currently processing iteration 256
Currently processing iteration 257
Currently processing iteration 258
Currently processing iteration 259
Currently processing iteration 260
Currently processing iteration 261
Currently processing iteration 262
Currently processing iteration 263
Currently processing iteration 264
Currently processing iteration 265
Currently processing iteration 266
Currently processing iteration 267
Currently processing iteration 268
Currently processing iteration 269
Currently processing iteration 270
Currently processing iteration 271
Currently processing iteration 272
Currently processing iteration 273
Currently processing iteration 274
Currently processing iteration 275
Currently processing iteration 276
Currently processing iteration 277
Currently processing iteration 278
Currently processing iteration 279
Currently processing iteration 280
Currently processing iteration 281
Currently processing iteration 282
Currently processing iteration 283
Currently processing iteration 284
Currently processing iteration 285
Currently processing iteration 286
Currently processing iteration 287
Currently processing iteration 288
Currently processing iteration 289
Currently processing iteration 290
Currently processing iteration 291
Currently processing iteration 292
Currently processing iteration 293
Currently processing iteration 294
Currently processing iteration 295
Currently processing iteration 296
Currently processing iteration 297
Currently processing iteration 298
Currently processing iteration 299
Currently processing iteration 300
Currently processing iteration 301
Currently processing iteration 302
Currently processing iteration 303
Currently processing iteration 304
Currently processing iteration 305
Currently processing iteration 306
Currently processing iteration 307
Currently processing iteration 308
Currently processing iteration 309
Currently processing iteration 310
Currently processing iteration 311
Currently processing iteration 312
Currently processing iteration 313
Currently processing iteration 314
Currently processing iteration 315
Currently processing iteration 316
Currently processing iteration 317
Currently processing iteration 318
Currently processing iteration 319
Currently processing iteration 320
Currently processing iteration 321
Currently processing iteration 322
Currently processing iteration 323
Currently processing iteration 324
Currently processing iteration 325
Currently processing iteration 326
Currently processing iteration 327
Currently processing iteration 328
Currently processing iteration 329
Currently processing iteration 330
Currently processing iteration 331
Currently processing iteration 332
Currently processing iteration 333
Currently processing iteration 334
Currently processing iteration 335
Currently processing iteration 336
Currently processing iteration 337
Currently processing iteration 338
Currently processing iteration 339
Currently processing iteration 340
Currently processing iteration 341
Currently processing iteration 342
Currently processing iteration 343
Currently processing iteration 344
Currently processing iteration 345
Currently processing iteration 346
Currently processing iteration 347
Currently processing iteration 348
Currently processing iteration 349
Currently processing iteration 350
Currently processing iteration 351
Currently processing iteration 352
Currently processing iteration 353
Currently processing iteration 354
Currently processing iteration 355
Currently processing iteration 356
Currently processing iteration 357
Currently processing iteration 358
Currently processing iteration 359
Currently processing iteration 360
Currently processing iteration 361
Currently processing iteration 362
Currently processing iteration 363
Currently processing iteration 364
Currently processing iteration 365
Currently processing iteration 366
Currently processing iteration 367
Currently processing iteration 368
Currently processing iteration 369
Currently processing iteration 370
Currently processing iteration 371
Currently processing iteration 372
Currently processing iteration 373
Currently processing iteration 374
Currently processing iteration 375
Currently processing iteration 376
Currently processing iteration 377
Currently processing iteration 378
Currently processing iteration 379
Currently processing iteration 380
Currently processing iteration 381
Currently processing iteration 382
Currently processing iteration 383
Currently processing iteration 384
Currently processing iteration 385
Currently processing iteration 386
Currently processing iteration 387
Currently processing iteration 388
Currently processing iteration 389
Currently processing iteration 390
Currently processing iteration 391
Currently processing iteration 392
Currently processing iteration 393
Currently processing iteration 394
Currently processing iteration 395
Currently processing iteration 396
Currently processing iteration 397
Currently processing iteration 398
Currently processing iteration 399
Currently processing iteration 400
Currently processing iteration 401
Currently processing iteration 402
Currently processing iteration 403
Currently processing iteration 404
Currently processing iteration 405
Currently processing iteration 406
Currently processing iteration 407
Currently processing iteration 408
Currently processing iteration 409
Currently processing iteration 410
Currently processing iteration 411
Currently processing iteration 412
Currently processing iteration 413
Currently processing iteration 414
Currently processing iteration 415
Currently processing iteration 416
Currently processing iteration 417
Currently processing iteration 418
Currently processing iteration 419
Currently processing iteration 420
Currently processing iteration 421
Currently processing iteration 422
Currently processing iteration 423
Currently processing iteration 424
Currently processing iteration 425
Currently processing iteration 426
Currently processing iteration 427
Currently processing iteration 428
Currently processing iteration 429
Currently processing iteration 430
Currently processing iteration 431
Currently processing iteration 432
Currently processing iteration 433
Currently processing iteration 434
Currently processing iteration 435
Currently processing iteration 436
Currently processing iteration 437
Currently processing iteration 438
Currently processing iteration 439
Currently processing iteration 440
Currently processing iteration 441
Currently processing iteration 442
Currently processing iteration 443
Currently processing iteration 444
Currently processing iteration 445
Currently processing iteration 446
Currently processing iteration 447
Currently processing iteration 448
Currently processing iteration 449
Currently processing iteration 450
Currently processing iteration 451
Currently processing iteration 452
Currently processing iteration 453
Currently processing iteration 454
Currently processing iteration 455
Currently processing iteration 456
Currently processing iteration 457
Currently processing iteration 458
Currently processing iteration 459
Currently processing iteration 460
Currently processing iteration 461
Currently processing iteration 462
Currently processing iteration 463
Currently processing iteration 464
Currently processing iteration 465
Currently processing iteration 466
Currently processing iteration 467
Currently processing iteration 468
Currently processing iteration 469
Currently processing iteration 470
Currently processing iteration 471
Currently processing iteration 472
Currently processing iteration 473
Currently processing iteration 474
Currently processing iteration 475
Currently processing iteration 476
Currently processing iteration 477
Currently processing iteration 478
Currently processing iteration 479
Currently processing iteration 480
Currently processing iteration 481
Currently processing iteration 482
Currently processing iteration 483
Currently processing iteration 484
Currently processing iteration 485
Currently processing iteration 486
Currently processing iteration 487
Currently processing iteration 488
Currently processing iteration 489
Currently processing iteration 490
Currently processing iteration 491
Currently processing iteration 492
Currently processing iteration 493
Currently processing iteration 494
Currently processing iteration 495
Currently processing iteration 496
Currently processing iteration 497
Currently processing iteration 498
Currently processing iteration 499

KeyError: 'data'