In [70]:
import httpx
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime
import psycopg

In [53]:
api_url = 'https://api.opendota.com/api'

In [ ]:
match = httpx.get(f'{api_url}/matches/8655549306').json()

In [ ]:
keys = pd.DataFrame(match.keys())

In [14]:
keys[0]

0                     version
1                    match_id
2                  teamfights
3                      pauses
4                  objectives
5                        chat
6            radiant_gold_adv
7              radiant_xp_adv
8                   cosmetics
9               draft_timings
10                    players
11                   leagueid
12                 start_time
13                   duration
14                  series_id
15                series_type
16                    cluster
17                replay_salt
18                radiant_win
19          pre_game_duration
20              match_seq_num
21       tower_status_radiant
22          tower_status_dire
23    barracks_status_radiant
24       barracks_status_dire
25           first_blood_time
26                 lobby_type
27              human_players
28                  game_mode
29                      flags
30                     engine
31              radiant_score
32                 dire_score
33            radiant_team_id
34               radiant_name
35               radiant_logo
36      radiant_team_complete
37               dire_team_id
38                  dire_name
39                  dire_logo
40         dire_team_complete
41            radiant_captain
42               dire_captain
43                 picks_bans
44                    od_data
45                     league
46               radiant_team
47                  dire_team
48                   metadata
49                 replay_url
50                      patch
51                     region
52            all_word_counts
53             my_word_counts
54                      throw
55                       loss
Name: 0, dtype: object

In [ ]:
leagues = httpx.get(f'{api_url}/leagues').json()

In [20]:
leagues_df = pd.DataFrame(leagues)

In [24]:
leagues_df[leagues_df['tier'] == 'professional']

,leagueid,ticket,banner,tier,name
0,174,None,None,professional,AsianCyberGames SEA Invitational - BEST OF THE...
1,176,None,None,professional,Netolic Pro League 5 - West
2,177,None,None,professional,Netolic Pro League 5 - East
3,184,None,None,professional,MLG T.K.O.
4,186,None,None,professional,1ª Copa BoraDota
...,...,...,...,...,...
9272,10551,None,None,professional,joinDOTA Turbo Masters
9274,1069,None,None,professional,Sweaty Cup 2
9282,1008,None,None,professional,0
9286,4632,None,None,professional,SGC 2016
9297,1637,None,None,professional,UCL-Moscow Cup

In [46]:
leagues_df[leagues_df['name'].str.contains('BLAST')]

,leagueid,ticket,banner,tier,name
2782,11979,None,None,professional,BLAST Bounty Hunt
6450,17414,None,None,professional,BLAST SLAM I
7363,18706,None,None,professional,BLAST Slam IV: China Closed Qualifier
7620,19148,None,None,professional,BLAST Slam VI China Qualifier
8258,18830,None,None,professional,BLAST Slam V: China Closed Qualifier
8690,19099,None,None,professional,BLAST SLAM VI

In [47]:
soup = BeautifulSoup('<div class="gridTable tournamentCard Tierless NoGameIcon"><div class="gridHeader"><div class="gridCell Series"><abbr title="Series">S</abbr></div><div class="gridCell">Tournament</div><div class="gridCell">Date</div><div class="gridCell Prize">Prize&nbsp;Pool</div><div class="gridCell">Location</div><div class="gridCell"><abbr title="Number of Participants">P#</abbr></div><div class="gridCell">Winner</div><div class="gridCell">Runner-up</div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/DreamLeague" title="DreamLeague"><img alt="DreamLeague" src="/commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/50px-DreamLeague_2023_icon_lightmode.png" decoding="async" width="50" height="42" srcset="/commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/75px-DreamLeague_2023_icon_lightmode.png 1.5x, /commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/100px-DreamLeague_2023_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/DreamLeague" title="DreamLeague"><img alt="DreamLeague" src="/commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/50px-DreamLeague_2023_icon_darkmode.png" decoding="async" width="50" height="42" srcset="/commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/75px-DreamLeague_2023_icon_darkmode.png 1.5x, /commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/100px-DreamLeague_2023_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/DreamLeague/27" title="DreamLeague/27">DreamLeague Season 27</a></div><div class="gridCell EventDetails Date Header">Dec 10 - 21, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><a href="/dota2/Category:Europe" title="Europe"><img alt="Europe" src="/commons/images/thumb/f/f3/Eu_hd.png/36px-Eu_hd.png" decoding="async" width="36" height="24" srcset="/commons/images/thumb/f/f3/Eu_hd.png/54px-Eu_hd.png 1.5x, /commons/images/thumb/f/f3/Eu_hd.png/72px-Eu_hd.png 2x"></a></span>&nbsp;Europe</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">24</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Yandex" title="Team Yandex"><img alt="" src="/commons/images/thumb/e/e9/Team_Yandex_lightmode.png/56px-Team_Yandex_lightmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/e/e9/Team_Yandex_lightmode.png/84px-Team_Yandex_lightmode.png 1.5x, /commons/images/thumb/e/e9/Team_Yandex_lightmode.png/112px-Team_Yandex_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Yandex" title="Team Yandex"><img alt="" src="/commons/images/thumb/5/5d/Team_Yandex_darkmode.png/60px-Team_Yandex_darkmode.png" decoding="async" width="60" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/5d/Team_Yandex_darkmode.png/89px-Team_Yandex_darkmode.png 1.5x, /commons/images/thumb/5/5d/Team_Yandex_darkmode.png/119px-Team_Yandex_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Yandex" title="Team Yandex">Team Yandex</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/43px-Team_Spirit_2022_lightmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/64px-Team_Spirit_2022_lightmode.png 1.5x, /commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/86px-Team_Spirit_2022_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/43px-Team_Spirit_2022_darkmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/64px-Team_Spirit_2022_darkmode.png 1.5x, /commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/86px-Team_Spirit_2022_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Spirit" title="Team Spirit">Team Spirit</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/42px-BLAST_Slam_Dota_icon_lightmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/63px-BLAST_Slam_Dota_icon_lightmode.png 1.5x, /commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/85px-BLAST_Slam_Dota_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/42px-BLAST_Slam_Dota_icon_darkmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/63px-BLAST_Slam_Dota_icon_darkmode.png 1.5x, /commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/85px-BLAST_Slam_Dota_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/BLAST/Slam/5" title="BLAST/Slam/5">BLAST Slam V</a></div><div class="gridCell EventDetails Date Header">Nov 25 - Dec 7, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><a href="/dota2/Category:Europe" title="Europe"><img alt="Europe" src="/commons/images/thumb/f/f3/Eu_hd.png/36px-Eu_hd.png" decoding="async" width="36" height="24" srcset="/commons/images/thumb/f/f3/Eu_hd.png/54px-Eu_hd.png 1.5x, /commons/images/thumb/f/f3/Eu_hd.png/72px-Eu_hd.png 2x"></a></span>&nbsp;Europe</span><span class="FlagText"><span class="flag"><img alt="China" src="/commons/images/thumb/0/01/Cn_hd.png/36px-Cn_hd.png" decoding="async" title="China" width="36" height="24" srcset="/commons/images/thumb/0/01/Cn_hd.png/54px-Cn_hd.png 1.5x, /commons/images/thumb/0/01/Cn_hd.png/72px-Cn_hd.png 2x"></span>&nbsp;Chengdu</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">12</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Yandex" title="Team Yandex"><img alt="" src="/commons/images/thumb/e/e9/Team_Yandex_lightmode.png/56px-Team_Yandex_lightmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/e/e9/Team_Yandex_lightmode.png/84px-Team_Yandex_lightmode.png 1.5x, /commons/images/thumb/e/e9/Team_Yandex_lightmode.png/112px-Team_Yandex_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Yandex" title="Team Yandex"><img alt="" src="/commons/images/thumb/5/5d/Team_Yandex_darkmode.png/60px-Team_Yandex_darkmode.png" decoding="async" width="60" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/5d/Team_Yandex_darkmode.png/89px-Team_Yandex_darkmode.png 1.5x, /commons/images/thumb/5/5d/Team_Yandex_darkmode.png/119px-Team_Yandex_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Yandex" title="Team Yandex">Team Yandex</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/PGL_Wallachia" title="PGL Wallachia"><img alt="PGL Wallachia" src="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/43px-PGL_Wallachia_icon_allmode.png" decoding="async" width="43" height="50" srcset="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/65px-PGL_Wallachia_icon_allmode.png 1.5x, /commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/86px-PGL_Wallachia_icon_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/PGL/Wallachia/6" title="PGL/Wallachia/6">PGL Wallachia Season 6</a></div><div class="gridCell EventDetails Date Header">Nov 15 - 23, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Romania" src="/commons/images/thumb/5/5c/Ro_hd.png/36px-Ro_hd.png" decoding="async" title="Romania" width="36" height="24" srcset="/commons/images/thumb/5/5c/Ro_hd.png/54px-Ro_hd.png 1.5x, /commons/images/thumb/5/5c/Ro_hd.png/72px-Ro_hd.png 2x"></span>&nbsp;Bucharest</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/MOUZ" title="MOUZ"><img alt="" src="/commons/images/thumb/c/c2/MOUZ_2021_allmode.png/47px-MOUZ_2021_allmode.png" decoding="async" width="47" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/c/c2/MOUZ_2021_allmode.png/71px-MOUZ_2021_allmode.png 1.5x, /commons/images/thumb/c/c2/MOUZ_2021_allmode.png/94px-MOUZ_2021_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/MOUZ" title="MOUZ">MOUZ</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/43px-Team_Spirit_2022_lightmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/64px-Team_Spirit_2022_lightmode.png 1.5x, /commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/86px-Team_Spirit_2022_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/43px-Team_Spirit_2022_darkmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/64px-Team_Spirit_2022_darkmode.png 1.5x, /commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/86px-Team_Spirit_2022_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Spirit" title="Team Spirit">Team Spirit</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/FISSURE_PLAYGROUND" title="FISSURE PLAYGROUND"><img alt="FISSURE PLAYGROUND" src="/commons/images/thumb/2/23/FISSURE_2024_icon_lightmode.png/50px-FISSURE_2024_icon_lightmode.png" decoding="async" width="50" height="35" srcset="/commons/images/thumb/2/23/FISSURE_2024_icon_lightmode.png/75px-FISSURE_2024_icon_lightmode.png 1.5x, /commons/images/thumb/2/23/FISSURE_2024_icon_lightmode.png/100px-FISSURE_2024_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/FISSURE_PLAYGROUND" title="FISSURE PLAYGROUND"><img alt="FISSURE PLAYGROUND" src="/commons/images/thumb/e/ee/FISSURE_2024_icon_darkmode.png/50px-FISSURE_2024_icon_darkmode.png" decoding="async" width="50" height="35" srcset="/commons/images/thumb/e/ee/FISSURE_2024_icon_darkmode.png/75px-FISSURE_2024_icon_darkmode.png 1.5x, /commons/images/thumb/e/ee/FISSURE_2024_icon_darkmode.png/100px-FISSURE_2024_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/FISSURE/PLAYGROUND/2" title="FISSURE/PLAYGROUND/2">FISSURE PLAYGROUND 2</a></div><div class="gridCell EventDetails Date Header">Oct 23 - Nov 2, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Serbia" src="/commons/images/thumb/7/7b/Rs_hd.png/36px-Rs_hd.png" decoding="async" title="Serbia" width="36" height="24" srcset="/commons/images/thumb/7/7b/Rs_hd.png/54px-Rs_hd.png 1.5x, /commons/images/thumb/7/7b/Rs_hd.png/72px-Rs_hd.png 2x"></span>&nbsp;Belgrade</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Falcons" title="Team Falcons"><img alt="" src="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/41px-Team_Falcons_2022_allmode.png" decoding="async" width="41" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/62px-Team_Falcons_2022_allmode.png 1.5x, /commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/83px-Team_Falcons_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Falcons" title="Team Falcons">Team Falcons</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/BetBoom_Team" title="BetBoom Team"><img alt="" src="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/56px-BetBoom_Team_2024_allmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/84px-BetBoom_Team_2024_allmode.png 1.5x, /commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/112px-BetBoom_Team_2024_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/BetBoom_Team" title="BetBoom Team">BetBoom Team</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/42px-BLAST_Slam_Dota_icon_lightmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/63px-BLAST_Slam_Dota_icon_lightmode.png 1.5x, /commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/85px-BLAST_Slam_Dota_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/42px-BLAST_Slam_Dota_icon_darkmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/63px-BLAST_Slam_Dota_icon_darkmode.png 1.5x, /commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/85px-BLAST_Slam_Dota_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/BLAST/Slam/4" title="BLAST/Slam/4">BLAST Slam IV</a></div><div class="gridCell EventDetails Date Header">Oct 14 - Nov 9, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><a href="/dota2/Category:Europe" title="Europe"><img alt="Europe" src="/commons/images/thumb/f/f3/Eu_hd.png/36px-Eu_hd.png" decoding="async" width="36" height="24" srcset="/commons/images/thumb/f/f3/Eu_hd.png/54px-Eu_hd.png 1.5x, /commons/images/thumb/f/f3/Eu_hd.png/72px-Eu_hd.png 2x"></a></span>&nbsp;Europe</span><span class="FlagText"><span class="flag"><img alt="Singapore" src="/commons/images/thumb/7/75/Sg_hd.png/36px-Sg_hd.png" decoding="async" title="Singapore" width="36" height="24" srcset="/commons/images/thumb/7/75/Sg_hd.png/54px-Sg_hd.png 1.5x, /commons/images/thumb/7/75/Sg_hd.png/72px-Sg_hd.png 2x"></span>&nbsp;Singapore</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">12</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Falcons" title="Team Falcons"><img alt="" src="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/41px-Team_Falcons_2022_allmode.png" decoding="async" width="41" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/62px-Team_Falcons_2022_allmode.png 1.5x, /commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/83px-Team_Falcons_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Falcons" title="Team Falcons">Team Falcons</a></span></div></span></div></div><div class="gridRow tournament-highlighted-bg"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/The_International" title="The International"><img alt="The International" src="/commons/images/thumb/6/6e/The_International_2025_aegis_allmode.png/50px-The_International_2025_aegis_allmode.png" decoding="async" width="50" height="49" srcset="/commons/images/thumb/6/6e/The_International_2025_aegis_allmode.png/75px-The_International_2025_aegis_allmode.png 1.5x, /commons/images/thumb/6/6e/The_International_2025_aegis_allmode.png/100px-The_International_2025_aegis_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/The_International/2025" title="The International/2025">The International 2025</a></div><div class="gridCell EventDetails Date Header">Sep 4 - 14, 2025</div><div class="gridCell EventDetails Prize Header">$2,881,791</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Germany" src="/commons/images/thumb/0/0c/De_hd.png/36px-De_hd.png" decoding="async" title="Germany" width="36" height="24" srcset="/commons/images/thumb/0/0c/De_hd.png/54px-De_hd.png 1.5x, /commons/images/thumb/0/0c/De_hd.png/72px-De_hd.png 2x"></span>&nbsp;Hamburg</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Falcons" title="Team Falcons"><img alt="" src="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/41px-Team_Falcons_2022_allmode.png" decoding="async" width="41" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/62px-Team_Falcons_2022_allmode.png 1.5x, /commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/83px-Team_Falcons_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Falcons" title="Team Falcons">Team Falcons</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Xtreme_Gaming" title="Xtreme Gaming"><img alt="" src="/commons/images/thumb/7/72/Xtreme_Gaming_%28China%29_allmode.png/50px-Xtreme_Gaming_%28China%29_allmode.png" decoding="async" width="50" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/7/72/Xtreme_Gaming_%28China%29_allmode.png/75px-Xtreme_Gaming_%28China%29_allmode.png 1.5x, /commons/images/thumb/7/72/Xtreme_Gaming_%28China%29_allmode.png/100px-Xtreme_Gaming_%28China%29_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Xtreme_Gaming" title="Xtreme Gaming">Xtreme Gaming</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/FISSURE_Universe" title="FISSURE Universe"><img alt="FISSURE Universe" src="/commons/images/thumb/f/f5/FISSURE_Universe_Episode_6_allmode.png/50px-FISSURE_Universe_Episode_6_allmode.png" decoding="async" width="50" height="35" srcset="/commons/images/thumb/f/f5/FISSURE_Universe_Episode_6_allmode.png/75px-FISSURE_Universe_Episode_6_allmode.png 1.5x, /commons/images/thumb/f/f5/FISSURE_Universe_Episode_6_allmode.png/100px-FISSURE_Universe_Episode_6_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/FISSURE/Universe/6" title="FISSURE/Universe/6">FISSURE Universe: Episode 6</a></div><div class="gridCell EventDetails Date Header">Aug 19 - 24, 2025</div><div class="gridCell EventDetails Prize Header">$250,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><a href="/dota2/Category:Europe" title="Europe"><img alt="Europe" src="/commons/images/thumb/f/f3/Eu_hd.png/36px-Eu_hd.png" decoding="async" width="36" height="24" srcset="/commons/images/thumb/f/f3/Eu_hd.png/54px-Eu_hd.png 1.5x, /commons/images/thumb/f/f3/Eu_hd.png/72px-Eu_hd.png 2x"></a></span>&nbsp;Europe</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">10</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Falcons" title="Team Falcons"><img alt="" src="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/41px-Team_Falcons_2022_allmode.png" decoding="async" width="41" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/62px-Team_Falcons_2022_allmode.png 1.5x, /commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/83px-Team_Falcons_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Falcons" title="Team Falcons">Team Falcons</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/43px-Team_Spirit_2022_lightmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/64px-Team_Spirit_2022_lightmode.png 1.5x, /commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/86px-Team_Spirit_2022_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/43px-Team_Spirit_2022_darkmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/64px-Team_Spirit_2022_darkmode.png 1.5x, /commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/86px-Team_Spirit_2022_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Spirit" title="Team Spirit">Team Spirit</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/Clavision_Masters" title="Clavision Masters"><img alt="Clavision Masters" src="/commons/images/thumb/a/af/Clavision_Masters_2025_allmode.png/50px-Clavision_Masters_2025_allmode.png" decoding="async" width="50" height="39" srcset="/commons/images/thumb/a/af/Clavision_Masters_2025_allmode.png/75px-Clavision_Masters_2025_allmode.png 1.5x, /commons/images/thumb/a/af/Clavision_Masters_2025_allmode.png/100px-Clavision_Masters_2025_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/Clavision/Masters/2025" title="Clavision/Masters/2025">Clavision Masters 2025: Snow-Ruyi</a></div><div class="gridCell EventDetails Date Header">Jul 28 - Aug 3, 2025</div><div class="gridCell EventDetails Prize Header">$700,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="China" src="/commons/images/thumb/0/01/Cn_hd.png/36px-Cn_hd.png" decoding="async" title="China" width="36" height="24" srcset="/commons/images/thumb/0/01/Cn_hd.png/54px-Cn_hd.png 1.5x, /commons/images/thumb/0/01/Cn_hd.png/72px-Cn_hd.png 2x"></span>&nbsp;Zhangjiakou</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">10</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Tidebound" title="Team Tidebound"><img alt="" src="/commons/images/thumb/5/50/Team_Tidebound_allmode.png/62px-Team_Tidebound_allmode.png" decoding="async" width="62" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/50/Team_Tidebound_allmode.png/94px-Team_Tidebound_allmode.png 1.5x, /commons/images/thumb/5/50/Team_Tidebound_allmode.png/125px-Team_Tidebound_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Tidebound" title="Team Tidebound">Team Tidebound</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/Esports_World_Cup" title="Esports World Cup"><img alt="Esports World Cup" src="/commons/images/thumb/e/eb/Esports_World_Cup_icon_lightmode.png/50px-Esports_World_Cup_icon_lightmode.png" decoding="async" width="50" height="10" srcset="/commons/images/thumb/e/eb/Esports_World_Cup_icon_lightmode.png/75px-Esports_World_Cup_icon_lightmode.png 1.5x, /commons/images/thumb/e/eb/Esports_World_Cup_icon_lightmode.png/100px-Esports_World_Cup_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/Esports_World_Cup" title="Esports World Cup"><img alt="Esports World Cup" src="/commons/images/thumb/5/5f/Esports_World_Cup_icon_darkmode.png/50px-Esports_World_Cup_icon_darkmode.png" decoding="async" width="50" height="10" srcset="/commons/images/thumb/5/5f/Esports_World_Cup_icon_darkmode.png/75px-Esports_World_Cup_icon_darkmode.png 1.5x, /commons/images/thumb/5/5f/Esports_World_Cup_icon_darkmode.png/100px-Esports_World_Cup_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/Esports_World_Cup/2025" title="Esports World Cup/2025">Esports World Cup 2025</a></div><div class="gridCell EventDetails Date Header">Jul 8 - 19, 2025</div><div class="gridCell EventDetails Prize Header">$3,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Saudi Arabia" src="/commons/images/thumb/d/d6/Sa_hd.png/36px-Sa_hd.png" decoding="async" title="Saudi Arabia" width="36" height="24" srcset="/commons/images/thumb/d/d6/Sa_hd.png/54px-Sa_hd.png 1.5x, /commons/images/thumb/d/d6/Sa_hd.png/72px-Sa_hd.png 2x"></span>&nbsp;Riyadh</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/43px-Team_Spirit_2022_lightmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/64px-Team_Spirit_2022_lightmode.png 1.5x, /commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/86px-Team_Spirit_2022_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/43px-Team_Spirit_2022_darkmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/64px-Team_Spirit_2022_darkmode.png 1.5x, /commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/86px-Team_Spirit_2022_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Spirit" title="Team Spirit">Team Spirit</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Falcons" title="Team Falcons"><img alt="" src="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/41px-Team_Falcons_2022_allmode.png" decoding="async" width="41" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/62px-Team_Falcons_2022_allmode.png 1.5x, /commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/83px-Team_Falcons_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Falcons" title="Team Falcons">Team Falcons</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/PGL_Wallachia" title="PGL Wallachia"><img alt="PGL Wallachia" src="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/43px-PGL_Wallachia_icon_allmode.png" decoding="async" width="43" height="50" srcset="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/65px-PGL_Wallachia_icon_allmode.png 1.5x, /commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/86px-PGL_Wallachia_icon_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/PGL/Wallachia/5" title="PGL/Wallachia/5">PGL Wallachia Season 5</a></div><div class="gridCell EventDetails Date Header">Jun 21 - 29, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Romania" src="/commons/images/thumb/5/5c/Ro_hd.png/36px-Ro_hd.png" decoding="async" title="Romania" width="36" height="24" srcset="/commons/images/thumb/5/5c/Ro_hd.png/54px-Ro_hd.png 1.5x, /commons/images/thumb/5/5c/Ro_hd.png/72px-Ro_hd.png 2x"></span>&nbsp;Bucharest</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/BetBoom_Team" title="BetBoom Team"><img alt="" src="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/56px-BetBoom_Team_2024_allmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/84px-BetBoom_Team_2024_allmode.png 1.5x, /commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/112px-BetBoom_Team_2024_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/BetBoom_Team" title="BetBoom Team">BetBoom Team</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Gaimin_Gladiators" title="Gaimin Gladiators"><img alt="" src="/commons/images/thumb/7/78/Gladiators_2022_allmode.png/30px-Gladiators_2022_allmode.png" decoding="async" width="30" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/7/78/Gladiators_2022_allmode.png/45px-Gladiators_2022_allmode.png 1.5x, /commons/images/thumb/7/78/Gladiators_2022_allmode.png/60px-Gladiators_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Gaimin_Gladiators" title="Gaimin Gladiators">Gaimin Gladiators</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/DreamLeague" title="DreamLeague"><img alt="DreamLeague" src="/commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/50px-DreamLeague_2023_icon_lightmode.png" decoding="async" width="50" height="42" srcset="/commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/75px-DreamLeague_2023_icon_lightmode.png 1.5x, /commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/100px-DreamLeague_2023_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/DreamLeague" title="DreamLeague"><img alt="DreamLeague" src="/commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/50px-DreamLeague_2023_icon_darkmode.png" decoding="async" width="50" height="42" srcset="/commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/75px-DreamLeague_2023_icon_darkmode.png 1.5x, /commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/100px-DreamLeague_2023_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/DreamLeague/Season_26" title="DreamLeague/Season 26">DreamLeague Season 26</a></div><div class="gridCell EventDetails Date Header">May 19 - Jun 1, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><a href="/dota2/Category:Europe" title="Europe"><img alt="Europe" src="/commons/images/thumb/f/f3/Eu_hd.png/36px-Eu_hd.png" decoding="async" width="36" height="24" srcset="/commons/images/thumb/f/f3/Eu_hd.png/54px-Eu_hd.png 1.5x, /commons/images/thumb/f/f3/Eu_hd.png/72px-Eu_hd.png 2x"></a></span>&nbsp;Europe</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/PARIVISION" title="PARIVISION"><img alt="" src="/commons/images/thumb/9/9d/PARIVISION_allmode.png/56px-PARIVISION_allmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/9/9d/PARIVISION_allmode.png/85px-PARIVISION_allmode.png 1.5x, /commons/images/thumb/9/9d/PARIVISION_allmode.png/113px-PARIVISION_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/PARIVISION" title="PARIVISION">PARIVISION</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/BetBoom_Team" title="BetBoom Team"><img alt="" src="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/56px-BetBoom_Team_2024_allmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/84px-BetBoom_Team_2024_allmode.png 1.5x, /commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/112px-BetBoom_Team_2024_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/BetBoom_Team" title="BetBoom Team">BetBoom Team</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/42px-BLAST_Slam_Dota_icon_lightmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/63px-BLAST_Slam_Dota_icon_lightmode.png 1.5x, /commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/85px-BLAST_Slam_Dota_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/42px-BLAST_Slam_Dota_icon_darkmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/63px-BLAST_Slam_Dota_icon_darkmode.png 1.5x, /commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/85px-BLAST_Slam_Dota_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/BLAST/Slam/3" title="BLAST/Slam/3">BLAST Slam III</a></div><div class="gridCell EventDetails Date Header">May 6 - 11, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Denmark" src="/commons/images/thumb/7/7d/Dk_hd.png/36px-Dk_hd.png" decoding="async" title="Denmark" width="36" height="24" srcset="/commons/images/thumb/7/7d/Dk_hd.png/54px-Dk_hd.png 1.5x, /commons/images/thumb/7/7d/Dk_hd.png/72px-Dk_hd.png 2x"></span>&nbsp;Copenhagen</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">10</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Falcons" title="Team Falcons"><img alt="" src="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/41px-Team_Falcons_2022_allmode.png" decoding="async" width="41" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/62px-Team_Falcons_2022_allmode.png 1.5x, /commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/83px-Team_Falcons_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Falcons" title="Team Falcons">Team Falcons</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/PGL_Wallachia" title="PGL Wallachia"><img alt="PGL Wallachia" src="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/43px-PGL_Wallachia_icon_allmode.png" decoding="async" width="43" height="50" srcset="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/65px-PGL_Wallachia_icon_allmode.png 1.5x, /commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/86px-PGL_Wallachia_icon_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/PGL/Wallachia/4" title="PGL/Wallachia/4">PGL Wallachia Season 4</a></div><div class="gridCell EventDetails Date Header">Apr 19 - 27, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Romania" src="/commons/images/thumb/5/5c/Ro_hd.png/36px-Ro_hd.png" decoding="async" title="Romania" width="36" height="24" srcset="/commons/images/thumb/5/5c/Ro_hd.png/54px-Ro_hd.png 1.5x, /commons/images/thumb/5/5c/Ro_hd.png/72px-Ro_hd.png 2x"></span>&nbsp;Bucharest</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Liquid" title="Team Liquid"><img alt="" src="/commons/images/thumb/0/01/Team_Liquid_2024_lightmode.png/44px-Team_Liquid_2024_lightmode.png" decoding="async" width="44" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/0/01/Team_Liquid_2024_lightmode.png/66px-Team_Liquid_2024_lightmode.png 1.5x, /commons/images/thumb/0/01/Team_Liquid_2024_lightmode.png/88px-Team_Liquid_2024_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Liquid" title="Team Liquid"><img alt="" src="/commons/images/thumb/5/59/Team_Liquid_2024_darkmode.png/44px-Team_Liquid_2024_darkmode.png" decoding="async" width="44" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/59/Team_Liquid_2024_darkmode.png/66px-Team_Liquid_2024_darkmode.png 1.5x, /commons/images/thumb/5/59/Team_Liquid_2024_darkmode.png/88px-Team_Liquid_2024_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Liquid" title="Team Liquid">Team Liquid</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/PARIVISION" title="PARIVISION"><img alt="" src="/commons/images/thumb/9/9d/PARIVISION_allmode.png/56px-PARIVISION_allmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/9/9d/PARIVISION_allmode.png/85px-PARIVISION_allmode.png 1.5x, /commons/images/thumb/9/9d/PARIVISION_allmode.png/113px-PARIVISION_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/PARIVISION" title="PARIVISION">PARIVISION</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/ESL_One" title="ESL One"><img alt="ESL One" src="/commons/images/thumb/1/14/ESL_One_2025_icon_lightmode.png/43px-ESL_One_2025_icon_lightmode.png" decoding="async" width="43" height="50" srcset="/commons/images/thumb/1/14/ESL_One_2025_icon_lightmode.png/64px-ESL_One_2025_icon_lightmode.png 1.5x, /commons/images/thumb/1/14/ESL_One_2025_icon_lightmode.png/85px-ESL_One_2025_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/ESL_One" title="ESL One"><img alt="ESL One" src="/commons/images/thumb/d/de/ESL_One_2025_icon_darkmode.png/43px-ESL_One_2025_icon_darkmode.png" decoding="async" width="43" height="50" srcset="/commons/images/thumb/d/de/ESL_One_2025_icon_darkmode.png/64px-ESL_One_2025_icon_darkmode.png 1.5x, /commons/images/thumb/d/de/ESL_One_2025_icon_darkmode.png/85px-ESL_One_2025_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/ESL_One/Raleigh/2025" title="ESL One/Raleigh/2025">ESL One Raleigh 2025</a></div><div class="gridCell EventDetails Date Header">Apr 7 - 13, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="United States" src="/commons/images/thumb/3/3b/Us_hd.png/36px-Us_hd.png" decoding="async" title="United States" width="36" height="24" srcset="/commons/images/thumb/3/3b/Us_hd.png/54px-Us_hd.png 1.5x, /commons/images/thumb/3/3b/Us_hd.png/72px-Us_hd.png 2x"></span>&nbsp;Raleigh</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">12</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/PARIVISION" title="PARIVISION"><img alt="" src="/commons/images/thumb/9/9d/PARIVISION_allmode.png/56px-PARIVISION_allmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/9/9d/PARIVISION_allmode.png/85px-PARIVISION_allmode.png 1.5x, /commons/images/thumb/9/9d/PARIVISION_allmode.png/113px-PARIVISION_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/PARIVISION" title="PARIVISION">PARIVISION</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/43px-Team_Spirit_2022_lightmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/64px-Team_Spirit_2022_lightmode.png 1.5x, /commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/86px-Team_Spirit_2022_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/43px-Team_Spirit_2022_darkmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/64px-Team_Spirit_2022_darkmode.png 1.5x, /commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/86px-Team_Spirit_2022_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Spirit" title="Team Spirit">Team Spirit</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/FISSURE_Universe" title="FISSURE Universe"><img alt="FISSURE Universe" src="/commons/images/thumb/1/19/FISSURE_Universe_Episode_4_allmode.png/50px-FISSURE_Universe_Episode_4_allmode.png" decoding="async" width="50" height="35" srcset="/commons/images/thumb/1/19/FISSURE_Universe_Episode_4_allmode.png/75px-FISSURE_Universe_Episode_4_allmode.png 1.5x, /commons/images/thumb/1/19/FISSURE_Universe_Episode_4_allmode.png/100px-FISSURE_Universe_Episode_4_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/FISSURE/Universe/4" title="FISSURE/Universe/4">FISSURE Universe: Episode 4</a></div><div class="gridCell EventDetails Date Header">Mar 22 - 30, 2025</div><div class="gridCell EventDetails Prize Header">$500,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><a href="/dota2/Category:Europe" title="Europe"><img alt="Europe" src="/commons/images/thumb/f/f3/Eu_hd.png/36px-Eu_hd.png" decoding="async" width="36" height="24" srcset="/commons/images/thumb/f/f3/Eu_hd.png/54px-Eu_hd.png 1.5x, /commons/images/thumb/f/f3/Eu_hd.png/72px-Eu_hd.png 2x"></a></span>&nbsp;Europe</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/BetBoom_Team" title="BetBoom Team"><img alt="" src="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/56px-BetBoom_Team_2024_allmode.png" decoding="async" width="56" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/84px-BetBoom_Team_2024_allmode.png 1.5x, /commons/images/thumb/5/5b/BetBoom_Team_2024_allmode.png/112px-BetBoom_Team_2024_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/BetBoom_Team" title="BetBoom Team">BetBoom Team</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Gaimin_Gladiators" title="Gaimin Gladiators"><img alt="" src="/commons/images/thumb/7/78/Gladiators_2022_allmode.png/30px-Gladiators_2022_allmode.png" decoding="async" width="30" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/7/78/Gladiators_2022_allmode.png/45px-Gladiators_2022_allmode.png 1.5x, /commons/images/thumb/7/78/Gladiators_2022_allmode.png/60px-Gladiators_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Gaimin_Gladiators" title="Gaimin Gladiators">Gaimin Gladiators</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image"><a href="/dota2/PGL_Wallachia" title="PGL Wallachia"><img alt="PGL Wallachia" src="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/43px-PGL_Wallachia_icon_allmode.png" decoding="async" width="43" height="50" srcset="/commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/65px-PGL_Wallachia_icon_allmode.png 1.5x, /commons/images/thumb/0/0c/PGL_Wallachia_icon_allmode.png/86px-PGL_Wallachia_icon_allmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/PGL/Wallachia/3" title="PGL/Wallachia/3">PGL Wallachia Season 3</a></div><div class="gridCell EventDetails Date Header">Mar 8 - 16, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Romania" src="/commons/images/thumb/5/5c/Ro_hd.png/36px-Ro_hd.png" decoding="async" title="Romania" width="36" height="24" srcset="/commons/images/thumb/5/5c/Ro_hd.png/54px-Ro_hd.png 1.5x, /commons/images/thumb/5/5c/Ro_hd.png/72px-Ro_hd.png 2x"></span>&nbsp;Bucharest</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Liquid" title="Team Liquid"><img alt="" src="/commons/images/thumb/0/01/Team_Liquid_2024_lightmode.png/44px-Team_Liquid_2024_lightmode.png" decoding="async" width="44" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/0/01/Team_Liquid_2024_lightmode.png/66px-Team_Liquid_2024_lightmode.png 1.5x, /commons/images/thumb/0/01/Team_Liquid_2024_lightmode.png/88px-Team_Liquid_2024_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Liquid" title="Team Liquid"><img alt="" src="/commons/images/thumb/5/59/Team_Liquid_2024_darkmode.png/44px-Team_Liquid_2024_darkmode.png" decoding="async" width="44" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/5/59/Team_Liquid_2024_darkmode.png/66px-Team_Liquid_2024_darkmode.png 1.5x, /commons/images/thumb/5/59/Team_Liquid_2024_darkmode.png/88px-Team_Liquid_2024_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Liquid" title="Team Liquid">Team Liquid</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/DreamLeague" title="DreamLeague"><img alt="DreamLeague" src="/commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/50px-DreamLeague_2023_icon_lightmode.png" decoding="async" width="50" height="42" srcset="/commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/75px-DreamLeague_2023_icon_lightmode.png 1.5x, /commons/images/thumb/2/2f/DreamLeague_2023_icon_lightmode.png/100px-DreamLeague_2023_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/DreamLeague" title="DreamLeague"><img alt="DreamLeague" src="/commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/50px-DreamLeague_2023_icon_darkmode.png" decoding="async" width="50" height="42" srcset="/commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/75px-DreamLeague_2023_icon_darkmode.png 1.5x, /commons/images/thumb/1/10/DreamLeague_2023_icon_darkmode.png/100px-DreamLeague_2023_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/DreamLeague/Season_25" title="DreamLeague/Season 25">DreamLeague Season 25</a></div><div class="gridCell EventDetails Date Header">Feb 16 - Mar 4, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><a href="/dota2/Category:Europe" title="Europe"><img alt="Europe" src="/commons/images/thumb/f/f3/Eu_hd.png/36px-Eu_hd.png" decoding="async" width="36" height="24" srcset="/commons/images/thumb/f/f3/Eu_hd.png/54px-Eu_hd.png 1.5x, /commons/images/thumb/f/f3/Eu_hd.png/72px-Eu_hd.png 2x"></a></span>&nbsp;Europe</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/43px-Team_Spirit_2022_lightmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/64px-Team_Spirit_2022_lightmode.png 1.5x, /commons/images/thumb/6/66/Team_Spirit_2022_lightmode.png/86px-Team_Spirit_2022_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Team_Spirit" title="Team Spirit"><img alt="" src="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/43px-Team_Spirit_2022_darkmode.png" decoding="async" width="43" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/64px-Team_Spirit_2022_darkmode.png 1.5x, /commons/images/thumb/8/80/Team_Spirit_2022_darkmode.png/86px-Team_Spirit_2022_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Spirit" title="Team Spirit">Team Spirit</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/42px-BLAST_Slam_Dota_icon_lightmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/63px-BLAST_Slam_Dota_icon_lightmode.png 1.5x, /commons/images/thumb/e/ef/BLAST_Slam_Dota_icon_lightmode.png/85px-BLAST_Slam_Dota_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/BLAST_Slam" title="BLAST Slam"><img alt="BLAST Slam" src="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/42px-BLAST_Slam_Dota_icon_darkmode.png" decoding="async" width="42" height="50" srcset="/commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/63px-BLAST_Slam_Dota_icon_darkmode.png 1.5x, /commons/images/thumb/7/72/BLAST_Slam_Dota_icon_darkmode.png/85px-BLAST_Slam_Dota_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/BLAST/Slam/2" title="BLAST/Slam/2">BLAST Slam II</a></div><div class="gridCell EventDetails Date Header">Feb 4 - 9, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Denmark" src="/commons/images/thumb/7/7d/Dk_hd.png/36px-Dk_hd.png" decoding="async" title="Denmark" width="36" height="24" srcset="/commons/images/thumb/7/7d/Dk_hd.png/54px-Dk_hd.png 1.5x, /commons/images/thumb/7/7d/Dk_hd.png/72px-Dk_hd.png 2x"></span>&nbsp;Copenhagen</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">10</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Gaimin_Gladiators" title="Gaimin Gladiators"><img alt="" src="/commons/images/thumb/7/78/Gladiators_2022_allmode.png/30px-Gladiators_2022_allmode.png" decoding="async" width="30" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/7/78/Gladiators_2022_allmode.png/45px-Gladiators_2022_allmode.png 1.5x, /commons/images/thumb/7/78/Gladiators_2022_allmode.png/60px-Gladiators_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Gaimin_Gladiators" title="Gaimin Gladiators">Gaimin Gladiators</a></span></div></span></div></div><div class="gridRow"><div class="gridCell Tournament Header"><span class="league-icon-small-image lightmode"><a href="/dota2/FISSURE_PLAYGROUND" title="FISSURE PLAYGROUND"><img alt="FISSURE PLAYGROUND" src="/commons/images/thumb/2/23/FISSURE_2024_icon_lightmode.png/50px-FISSURE_2024_icon_lightmode.png" decoding="async" width="50" height="35" srcset="/commons/images/thumb/2/23/FISSURE_2024_icon_lightmode.png/75px-FISSURE_2024_icon_lightmode.png 1.5x, /commons/images/thumb/2/23/FISSURE_2024_icon_lightmode.png/100px-FISSURE_2024_icon_lightmode.png 2x"></a></span><span class="league-icon-small-image darkmode"><a href="/dota2/FISSURE_PLAYGROUND" title="FISSURE PLAYGROUND"><img alt="FISSURE PLAYGROUND" src="/commons/images/thumb/e/ee/FISSURE_2024_icon_darkmode.png/50px-FISSURE_2024_icon_darkmode.png" decoding="async" width="50" height="35" srcset="/commons/images/thumb/e/ee/FISSURE_2024_icon_darkmode.png/75px-FISSURE_2024_icon_darkmode.png 1.5x, /commons/images/thumb/e/ee/FISSURE_2024_icon_darkmode.png/100px-FISSURE_2024_icon_darkmode.png 2x"></a></span>&nbsp;&nbsp;<a href="/dota2/FISSURE/PLAYGROUND/1" title="FISSURE/PLAYGROUND/1">FISSURE PLAYGROUND 1</a></div><div class="gridCell EventDetails Date Header">Jan 24 - Feb 2, 2025</div><div class="gridCell EventDetails Prize Header">$1,000,000</div><div class="gridCell EventDetails Location Header"><span class="FlagText"><span class="flag"><img alt="Serbia" src="/commons/images/thumb/7/7b/Rs_hd.png/36px-Rs_hd.png" decoding="async" title="Serbia" width="36" height="24" srcset="/commons/images/thumb/7/7b/Rs_hd.png/54px-Rs_hd.png 1.5x, /commons/images/thumb/7/7b/Rs_hd.png/72px-Rs_hd.png 2x"></span>&nbsp;Belgrade</span></div><div class="gridCell EventDetails PlayerNumber Header"><span style="vertical-align:top">16</span><span class="PlayerNumberSuffix">&nbsp;participants</span></div><div class="gridCell Placement FirstPlace"><span title="First Place" class="Medal"><img alt="" src="/commons/images/1/10/Gold.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon team-template-lightmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/58px-Tundra_Esports_2020_lightmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/87px-Tundra_Esports_2020_lightmode.png 1.5x, /commons/images/thumb/1/13/Tundra_Esports_2020_lightmode.png/115px-Tundra_Esports_2020_lightmode.png 2x"></a></span><span class="team-template-image-icon team-template-darkmode"><a href="/dota2/Tundra_Esports" title="Tundra Esports"><img alt="" src="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/58px-Tundra_Esports_2020_darkmode.png" decoding="async" width="58" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/87px-Tundra_Esports_2020_darkmode.png 1.5x, /commons/images/thumb/6/6a/Tundra_Esports_2020_darkmode.png/115px-Tundra_Esports_2020_darkmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Tundra_Esports" title="Tundra Esports">Tundra Esports</a></span></div></span></div><div class="gridCell Placement SecondPlace"><span title="Second Place" class="Medal"><img alt="" src="/commons/images/0/0b/Silver.png" decoding="async" width="24" height="24">&nbsp;</span><span class="Participants"><div class="block-team"><span class="team-template-image-icon"><a href="/dota2/Team_Falcons" title="Team Falcons"><img alt="" src="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/41px-Team_Falcons_2022_allmode.png" decoding="async" width="41" height="50" style="vertical-align: middle" srcset="/commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/62px-Team_Falcons_2022_allmode.png 1.5x, /commons/images/thumb/8/83/Team_Falcons_2022_allmode.png/83px-Team_Falcons_2022_allmode.png 2x"></a></span><span class="name" style="text-overflow:ellipsis;overflow:hidden;white-space:pre"><a href="/dota2/Team_Falcons" title="Team Falcons">Team Falcons</a></span></div></span></div></div></div>')

In [50]:
tier_one_leagues = pd.DataFrame(columns=leagues_df.columns)
for div in soup.find_all('div', attrs={'class': 'gridCell Tournament Header'}):
    rows = leagues_df[leagues_df['name'].str.contains(div.find_all('a')[-1].getText())]
    tier_one_leagues = pd.concat([tier_one_leagues, rows], ignore_index=True)

In [51]:
tier_one_leagues

,leagueid,ticket,banner,tier,name
0,18988,None,None,professional,DreamLeague Season 27
1,18629,None,None,professional,DreamLeague Season 27 Qualifiers
2,19148,None,None,professional,BLAST Slam VI China Qualifier
3,18830,None,None,professional,BLAST Slam V: China Closed Qualifier
4,18038,None,None,professional,FISSURE PLAYGROUND 2 - Closed Qualifiers - EEU
5,18700,None,None,professional,FISSURE PLAYGROUND 2 - Closed Qualifiers - Ame...
6,18701,None,None,professional,FISSURE PLAYGROUND 2 - Closed Qualifiers - EEU...
7,18735,None,None,professional,FISSURE PLAYGROUND 2 - Closed Qualifiers - Ame...
8,18863,None,None,professional,FISSURE PLAYGROUND 2
9,18667,None,None,professional,FISSURE PLAYGROUND 2 - Closed Qualifiers - China
10,18668,None,None,professional,FISSURE PLAYGROUND 2 - Closed Qualifiers - Ame...
11,18669,None,None,excluded,FISSURE PLAYGROUND 2 - Closed Qualifiers - SEA
12,18670,None,None,professional,FISSURE PLAYGROUND 2 - Closed Qualifiers - WEU...
13,18634,None,None,excluded,FISSURE PLAYGROUND 2 - Open Qualifiers
14,18706,None,None,professional,BLAST Slam IV: China Closed Qualifier
15,18178,None,None,excluded,Road To The International 2025 - Open Qualifie...
16,18179,None,None,excluded,Road To The International 2025 - Open Qualifie...
17,18180,None,None,excluded,Road To The International 2025 - Open Qualifie...
18,18181,None,None,excluded,Road To The International 2025 - Open Qualifie...
19,18182,None,None,excluded,Road To The International 2025 - Open Qualifie...
20,18309,None,None,professional,Road To The International 2025 - Regional Qual...
21,18324,None,None,premium,The International 2025
22,18681,None,None,excluded,The International 2025 (Practice)
23,18304,None,None,professional,Road To The International 2025 - Regional Qual...
24,18305,None,None,professional,Road To The International 2025 - Regional Qual...
25,18306,None,None,professional,Road To The International 2025 - Regional Qual...
26,18307,None,None,professional,Road To The International 2025 - Regional Qual...
27,18308,None,None,professional,Road To The International 2025 - Regional Qual...
28,18186,None,None,excluded,Road To The International 2025 - Open Qualifie...
29,18210,None,None,professional,Esports World Cup 2025 Qualifiers
30,18375,None,None,professional,Esports World Cup 2025
31,17874,None,None,professional,DreamLeague Season 26 Qualifiers
32,18111,None,None,professional,DreamLeague Season 26
33,17629,None,None,professional,ESL One Raleigh 2025 Qualifiers
34,17795,None,None,professional,ESL One Raleigh 2025
35,17628,None,None,professional,DreamLeague Season 25 Qualifiers powered by Intel
36,17765,None,None,professional,DreamLeague Season 25 powered by Intel
37,17588,None,None,professional,FISSURE PLAYGROUND 1 - Dota

In [56]:
cols = {
"match_id": 3703866531,
"duration": 0,
"start_time": 0,
"radiant_team_id": 0,
"radiant_name": "string",
"dire_team_id": 0,
"dire_name": "string",
"leagueid": 0,
"league_name": "string",
"series_id": 0,
"series_type": 0,
"radiant_score": 0,
"dire_score": 0,
"radiant_win": True,
"radiant": True
}

In [65]:
tier_one_matches = pd.DataFrame(columns=cols.keys())
for idx, row in tier_one_leagues.iterrows():
    response = httpx.get(f'{api_url}/leagues/{row["leagueid"]}/matches').json()
    matches = pd.DataFrame(response)
    tier_one_matches = pd.concat([tier_one_matches, matches], ignore_index=True)

In [66]:
tier_one_matches_dt = tier_one_matches['start_time'].apply(lambda x: datetime.fromtimestamp(x))
tier_one_matches_dt

0      2025-12-21 19:17:01
1      2025-12-21 18:18:01
2      2025-12-21 17:06:01
3      2025-12-21 15:55:01
4      2025-12-21 13:35:01
               ...
3712   2025-01-24 13:02:46
3713   2025-01-24 11:57:13
3714   2025-01-24 11:19:31
3715   2025-01-24 10:01:12
3716   2025-01-24 10:00:52
Name: start_time, Length: 3717, dtype: datetime64[ns]

In [68]:
tier_one_matches.insert(2, 'start_date', tier_one_matches_dt)

In [69]:
tier_one_matches

,match_id,duration,start_date,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,radiant,radiant_team_name,dire_team_name
0,8615531269,2188,2025-12-21 19:17:01,1766341021,9823272,NaN,7119388,NaN,18988,NaN,1048811,2,20,9,True,NaN,None,None
1,8615442050,1496,2025-12-21 18:18:01,1766337481,7119388,NaN,9823272,NaN,18988,NaN,1048811,2,6,16,False,NaN,None,None
2,8615341751,2413,2025-12-21 17:06:01,1766333161,9823272,NaN,7119388,NaN,18988,NaN,1048811,2,39,16,True,NaN,None,None
3,8615212174,2264,2025-12-21 15:55:01,1766328901,7119388,NaN,9823272,NaN,18988,NaN,1048811,2,30,14,True,NaN,None,None
4,8614983405,2367,2025-12-21 13:35:01,1766320501,9572001,NaN,7119388,NaN,18988,NaN,1048747,1,19,25,False,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3712,8143150050,2164,2025-01-24 13:02:46,1737720166,2163,NaN,9498970,NaN,17588,NaN,943550,0,40,9,True,NaN,None,None
3713,8143081862,1734,2025-01-24 11:57:13,1737716233,9351740,NaN,8291895,NaN,17588,NaN,943538,0,36,11,True,NaN,None,None
3714,8143045634,3065,2025-01-24 11:19:31,1737713971,7119388,NaN,9634742,NaN,17588,NaN,943529,0,46,21,True,NaN,None,None
3715,8142981801,1491,2025-01-24 10:01:12,1737709272,8261500,NaN,9651185,NaN,17588,NaN,943515,0,3,20,False,NaN,None,None
3716,8142981335,2643,2025-01-24 10:00:52,1737709252,8597976,NaN,8599101,NaN,17588,NaN,943514,0,39,22,True,NaN,None,None